const items=[
['Butter Croissant','Pastries','₹145','Flaky cultured-butter layers.','🥐','Vegetarian','Bestseller'],['Strawberry Danish','Pastries','₹185','Jammy berries, vanilla crème.','🍓','Vegetarian','Bestseller'],['Almond Croissant','Breakfast','₹175','Almond frangipane, toasted flakes.','🥐','Vegetarian',''],['Pistachio Cruffin','Pastries','₹195','Pistachio cream in crisp layers.','🧁','Vegetarian','New'],['Berry Cloud Cake','Cakes','₹240','Vanilla sponge, berry cloud cream.','🍰','Eggless','Bestseller'],['Strawberry Shortcake','Cakes','₹260','Fresh berries and feather-light cream.','🎂','Eggless',''],['Rose Lychee Cake','Cakes','₹280','Rose mousse, lychee and raspberry.','🌸','Eggless','New'],['Chocolate Raspberry Slice','Cakes','₹250','Dark chocolate, bright raspberry.','🍫','Eggless',''],['Crème Brûlée','Desserts','₹220','Vanilla bean custard, caramel crackle.','🍮','Vegetarian',''],['Strawberry Tiramisu','Desserts','₹240','Mascarpone, berries and pink cocoa.','🍓','Vegetarian','Bestseller'],['Vanilla Panna Cotta','Desserts','₹210','Soft vanilla cream, berry compote.','🍨','Vegetarian',''],['Berry Pavlova','Desserts','₹230','Crisp meringue, cream, fruit.','🍓','Eggless','New'],['Classic Cappuccino','Coffee','₹160','Balanced espresso and silky milk.','☕','Vegetarian',''],['Vanilla Latte','Coffee','₹180','Madagascan vanilla, double espresso.','☕','Vegetarian',''],['Strawberry Cream Latte','Coffee','₹210','Strawberry milk, espresso, cream.','🥤','Vegetarian','Bestseller'],['Rose Vanilla Latte','Coffee','₹190','Floral, creamy and gently sweet.','🌹','Vegetarian',''],['Berry Fizz','Cold Drinks','₹175','Berries, basil and sparkling water.','🫧','Vegetarian',''],['Strawberry Iced Tea','Cold Drinks','₹165','Black tea, strawberry, lemon.','🧋','Vegetarian',''],['Pink Lemonade','Cold Drinks','₹150','Fresh lemon and rose syrup.','🍋','Vegetarian',''],['Iced Mocha','Cold Drinks','₹195','Cold espresso, cocoa and milk.','🧊','Vegetarian','']];
let cart=[]; const grid=document.querySelector('#menu-grid');
function showMenu(filter='All'){grid.innerHTML='';items.filter(x=>filter==='All'||x[1]===filter).forEach((x,i)=>{let card=document.createElement('article');card.className='menu-card';card.innerHTML=`${x[6]?`<span class="badge">${x[6]}</span>`:''}<div class="food-visual"><span>${x[4]}</span></div><h3>${x[0]}</h3><p>${x[3]}</p><div class="card-bottom"><div><span class="price">${x[2]}</span><small class="veg"> · ${x[5]}</small></div><button class="add" data-name="${x[0]}">Add to Order</button></div>`;grid.append(card)})}showMenu();
document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelector('.filters .active').classList.remove('active');b.classList.add('active');showMenu(b.dataset.filter)});
function addItem(name){let x=items.find(i=>i[0]===name), c=cart.find(i=>i.name===name);if(c)c.qty++;else cart.push({name,price:+x[2].replace('₹',''),icon:x[4],qty:1});renderCart();let t=document.querySelector('.toast');t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
grid.addEventListener('click',e=>{if(e.target.matches('.add'))addItem(e.target.dataset.name)});
function renderCart(){let box=document.querySelector('.cart-items'),count=cart.reduce((s,x)=>s+x.qty,0),sub=cart.reduce((s,x)=>s+x.qty*x.price,0),tax=Math.round(sub*.05);document.querySelector('.cart-count').textContent=count;document.querySelector('.cart-count').style.display=count?'block':'none';document.querySelector('.subtotal').textContent='₹'+sub;document.querySelector('.tax').textContent='₹'+tax;document.querySelector('.total-val').textContent=sub+tax;document.querySelector('.checkout').disabled=!count;box.innerHTML=cart.length?cart.map(x=>`<div class="cart-row"><div class="cart-icon">${x.icon}</div><div><h4>${x.name}</h4><small>₹${x.price}</small><div class="qty"><button data-change="-" data-name="${x.name}">−</button> ${x.qty} <button data-change="+" data-name="${x.name}">+</button></div></div><button class="remove" data-remove="${x.name}">Remove</button></div>`).join(''):'<div class="empty">Your bag is ready for something sweet.<br><span>🍓</span></div>'}
document.querySelector('.cart-items').onclick=e=>{let n=e.target.dataset.name;if(e.target.dataset.change){let x=cart.find(a=>a.name===n);x.qty+=e.target.dataset.change==='+'?1:-1;if(x.qty<1)cart=cart.filter(a=>a!==x);renderCart()}if(e.target.dataset.remove){cart=cart.filter(x=>x.name!==n);renderCart()}};
const drawer=document.querySelector('.cart-drawer'),overlay=document.querySelector('.overlay');function toggleCart(state){drawer.classList.toggle('open',state);overlay.classList.toggle('show',state);drawer.setAttribute('aria-hidden',!state)}document.querySelector('[data-cart]').onclick=()=>toggleCart(true);document.querySelector('.close-cart').onclick=()=>toggleCart(false);overlay.onclick=()=>toggleCart(false);document.querySelector('.checkout').onclick=()=>{if(cart.length){alert('Demo checkout: your Maison Fraise treats are reserved. No payment is taken.');cart=[];renderCart();toggleCart(false)}};
document.querySelector('#reservation-form').onsubmit=e=>{e.preventDefault();document.querySelector('.confirmation').classList.add('show')};document.querySelector('#close-confirm').onclick=()=>{document.querySelector('.confirmation').classList.remove('show');document.querySelector('#reservation-form').reset()};
document.querySelector('.hamburger').onclick=e=>{let nav=document.querySelector('.nav nav');nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',nav.classList.contains('open'))};document.querySelectorAll('.nav nav a').forEach(a=>a.onclick=()=>document.querySelector('.nav nav').classList.remove('open'));
window.addEventListener('scroll',()=>document.querySelector('.nav').classList.toggle('scrolled',scrollY>20));
let reviews=[...document.querySelectorAll('.testimonial')],dots=[...document.querySelectorAll('.dots button')],ri=0;function review(n){reviews[ri].classList.remove('active');dots[ri].classList.remove('active');ri=n;reviews[ri].classList.add('active');dots[ri].classList.add('active')}dots.forEach((d,i)=>d.onclick=()=>review(i));setInterval(()=>review((ri+1)%3),5500);
let counted=false;let obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&!counted){counted=true;document.querySelectorAll('[data-count]').forEach(el=>{let end=+el.dataset.count,start=0,steps=40;let id=setInterval(()=>{start+=Math.ceil(end/steps);if(start>=end){start=end;clearInterval(id)}el.textContent=start+(end===2000?'+':end===100?'%':'+' )},25)})}}),{threshold:.4});obs.observe(document.querySelector('.stats'));
document.querySelector('.newsletter').onsubmit=e=>{e.preventDefault();document.querySelector('.newsletter-msg').textContent='Sweet — you’re on the list!';e.target.reset()};
if(matchMedia('(pointer:fine)').matches){let g=document.querySelector('.cursor-glow');window.addEventListener('pointermove',e=>{g.style.left=e.clientX+'px';g.style.top=e.clientY+'px'});document.querySelectorAll('button,a,.menu-card').forEach(el=>el.addEventListener('mouseenter',()=>g.style.width=g.style.height='330px'));document.querySelectorAll('button,a,.menu-card').forEach(el=>el.addEventListener('mouseleave',()=>g.style.width=g.style.height='250px'))}